name: flutter_chat_gpt
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  intl: ^0.20.2
  retrofit: ^4.9.2
  dio: ^5.9.0
  flutter_loggy_dio: ^3.1.0
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  flutter_bloc: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  json_serializable: ^6.10.0
  retrofit_generator: ^10.2.1
  hive_ce_generator: ^1.11.0


flutter:

  uses-material-design: true




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700